### ISSUE TITLE
Feature Request - audiobook suppory

### ISSUE THREAD

**Issue by njakes** [dkanada/gelli#161] opened 2021-06-06 15:44 UTC
Would there be any way to enable the scanning of the book categories so Gelli can be used to listen to Audiobooks?

**Comment by dkanada** [comment] 2021-06-06 15:58
Duplicate of #59 so let's track it there.

**Closed by dkanada** 2021-06-06 15:58 UTC

**Comment by njakes** [comment] 2021-06-07 20:33
Sorry about that, I looked for an open request but didn't find one for some reason.  Must have not cleared the search filter all the way.
