### ISSUE TITLE
Only seeing first 100 albums

### ISSUE THREAD

**Issue by ylefebvre** [dkanada/gelli#5] opened 2020-06-05 14:40 UTC
Hi, download the APK from your app that was posted on the in a thread around the Jellyfin player. First thing I noticed is that I can only see 100 albums in the Album view. I don't see any way to move to the next "page". This seems to match the fact that Jellyfin shows me 100 albums at a time in web view, but is kind of limiting at the moment.

Thanks for developing this new app!

**Comment by dkanada** [comment] 2020-06-05 14:47
I can confirm your issue. The plan was to add infinite scroll at some point but haven't had the time to implement it yet. Right now I just use the search to find specific items, and randomize the album order for everything else.

**Comment by ylefebvre** [comment] 2020-06-05 14:48
Sorry, just saw list of known issue on main page. Should have read a bit more before posting this.

**Comment by dkanada** [comment] 2020-06-05 14:50
No worries! It's good to have the issues here for tracking purposes.

**Comment by andra5** [comment] 2020-07-01 11:50
https://github.com/dkanada/gelli/releases/tag/v1.0.1 
I think this can be closed

**Comment by dkanada** [comment] 2020-07-01 12:56
I'll close it since the issue was technically addressed, but expect improvements in the future because I'm not satisfied with the way I implemented the fix.

**Closed by dkanada** 2020-07-01 12:56 UTC
