### ISSUE TITLE
Show Artist Name in Now Playing Screen

### ISSUE THREAD

**Issue by moduraziel** [dkanada/gelli#138] opened 2021-04-20 14:22 UTC
Currently, when viewing the Now Playing screen it shows the song title with the album name underneath. An option to show the artist name instead of the album name would be nice.

**Comment by dkanada** [comment] 2021-05-03 14:51
Duplicate of #19 but I'm not opposed to adding it, so the original issue will stay open.

**Closed by dkanada** 2021-05-03 14:51 UTC
