### ISSUE TITLE
[Feature] integrate with Android 12/13 media player controls

### ISSUE THREAD

**Issue by ylefebvre** [dkanada/gelli#222] opened 2022-08-26 21:48 UTC
I love the Gelli application and use it regularly. That being said,  I would love to see it integrate with the Android 12 and 13 media player.  All of my other app that play integrate with it and Gelli keeps playing music in its own section.  I think that this lack of integration is also what makes Gelli not stop playing music when another app start playing.

![Screenshot_20220826-174457](https://user-images.githubusercontent.com/8749791/186995220-f8c8ddf1-3e4b-4249-a25d-e3e3903fb740.png)
 The image above shows my notification shade with the standard media player and Gelli standing on its own below.

**Comment by jakobkukla** [comment] 2022-08-27 01:00
There is a setting which toggles the notification layout. By default this is set to use the "classic" layout, which is what you are seeing here and what was common before Android 10 or so. Turning this off should lead to the desired behavior. 

Should we maybe use the newer layout by default @dkanada?

About the second issue: I'm not aware of any problems with audio focus (this is what Android calls automatically stopping media/music when another app takes over), I thought I solved those in a previous PR. Are you using the latest version? If so, could you please open another issue and describe the problem in detail? Thanks.

**Comment by dkanada** [comment] 2022-08-27 01:06
@jakobkukla I believe I *just* pushed a commit doing exactly that for unrelated reasons. Although I'm using Android 13 and haven't seen duplicate music controls anywhere, so who knows how that happened.

**Comment by jakobkukla** [comment] 2022-08-27 01:12
Just saw your commit, sry for the ping haha. No idea why duplicate notifications could be happening either. I just assumed it was an Android 13 issue since I was using 12 until recently and it was fine.

**Comment by ylefebvre** [comment] 2022-08-27 01:14
Indeed. Turning off the classic notification layout resolved the issue and my playback in Gelli now shows up in the OS-level media player.

With the classic layout, the Gelli notifications hangs around even when you start playback of another app (like a podcast or music). If Gelli is not playing, I am able to swipe its classic notification away, but otherwise it will stick around for some time.

While changing the default layout might help new users, it won't help current users of the app on the latest versions of Android, no? Perhaps a prompt for users on newer Android with the classic layout asking them if they'd like to switch over? I never personally thought of looking in the options for this and I consider myself a fairly savvy Android user.

I tried reproducing the second issue I mentioned now with the classic layout and the non-classic layout and it's not doing it, but I will open a separate issue if it happens again.

**Comment by dkanada** [comment] 2022-08-28 00:12
@ylefebvre I have disabled the custom notifications on newer versions of Android for other reasons. If you eventually reproduce the other bug feel free to open a second issue but the first one should be resolved with the next update.

**Closed by dkanada** 2022-08-28 00:12 UTC
