### ISSUE TITLE
Attempting to transcode crashes the application

### ISSUE THREAD

**Issue by Pecomare** [dkanada/gelli#207] opened 2022-03-30 09:39 UTC
Since I upgraded my Jellyfin server to 10.8.0-beta1, any attempt to listen to a song through transcoding (by setting a max bitrate, since just unchecking a direct play codec doesn't force transcoding at the moment of writing the ticket) crashes the app with a "Couldn't play this song." toast.
Besides, the app constantly crashes after this fatal error (it is resuming its stream after all), and I need to clear the app storage to get to a clean state.
There doesn't seem to be any issue when direct playing.
I also tested with Finamp, the web client and the official app and I didn't see any issue there.

Phone: OnePlus 6T
Android version: 11
Operating System: OxygenOS 11.1.2.2
Gelli version: 1.3.2 from F-Droid
Jellyfin version: 10.8.0-beta1 through Podman (official image on docker.io)

I ran some logcat of the app when launching it in that constant-crash state, so I'm not sure if the start of the logs is useful, I don't even know if you can extract anything from these logs, it's my first time using logcat (ran logcat | grep com.dkanada.gramophone).
I also looked at Jellyfin's logs when trying to listen to a transcode. However, there is no transcoding log. I still posted the relevant lines in the log file.

Note: I changed the URL, API ID and user name.

logcat:
```
03-30 10:07:45.026  1210  4475 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.dkanada.gramophone/.activities.SplashActivity bnds=[167,833][302,968]} from uid 10256 pid 25196
03-30 10:07:45.045  1210  1614 D OpRestartProcessManager: updateSelf :  com.dkanada.gramophone, size : 30
03-30 10:07:45.053  1210  1627 I ActivityManager: Start proc 15303:com.dkanada.gramophone/u0a436 for pre-top-activity {com.dkanada.gramophone/com.dkanada.gramophone.activities.SplashActivity}
03-30 10:07:45.054  1210  1615 D OPFD_CTRL_SVC: [2]handle Starting Window for { com.dkanada.gramophone }, Dark? false
03-30 10:07:45.060  1221 19385 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 126 cmd: iop_start -1 com.dkanada.gramophone /data/app/~~8cuooyHaxULdUNCs1_4GVQ==/com.dkanada.gramophone-M5JCBdbkjpn0eeGckNdQ_g== false
03-30 10:07:45.064  1221 19387 E ANDR-RAMBOOST_SERVER: ramboost cmd_len = 129 cmd: iop_start 15303 com.dkanada.gramophone /data/app/~~8cuooyHaxULdUNCs1_4GVQ==/com.dkanada.gramophone-M5JCBdbkjpn0eeGckNdQ_g== false
03-30 10:07:45.065  1210  9909 D OpColorDisplayService: frontPackageChanged: com.dkanada.gramophone
03-30 10:07:45.065  1210  9909 D OpProximityController: noteFrontPackageChanged pkg:com.dkanada.gramophone uid:10436 lpkg:com.teslacoilsw.launcher luid:10256
03-30 10:07:45.066  1210  9909 D OpQuickReply: setQuickReplyResumed focusedApp ActivityRecord{d4aff91 u0 com.dkanada.gramophone/.activities.SplashActivity t10281} pkgName com.dkanada.gramophone
03-30 10:07:45.112 15303 15303 I chatty  : uid=10436(com.dkanada.gramophone) identical 1 line
03-30 10:07:45.207 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/System/Info?format=json
03-30 10:07:45.209  1210  1631 D ArtManagerInternalImpl: /data/misc/iorapd/com.dkanada.gramophone/15/com.dkanada.gramophone.activities.SplashActivity/compiled_traces/compiled_trace.pb doesn't exist
03-30 10:07:45.210  1210  1689 I ===> HoustonPackage: addLaunchTimeInfo: for com.dkanada.gramophone/.activities.SplashActivity isCold:true launchTime:182
03-30 10:07:45.210  1210  1689 I 322     : com.dkanada.gramophone#38#182
03-30 10:07:45.210  1210  1631 I ActivityTaskManager: Displayed com.dkanada.gramophone/.activities.SplashActivity: +182ms
03-30 10:07:45.211 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/System/Info?format=json
03-30 10:07:45.225  2407  2407 I PhoneStatusBarView: isFullAndNotchEnabled() isFullMode=false pkg=com.dkanada.gramophone isCameraNotchIgnoreSetting=false, uid=10436
03-30 10:07:45.621 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/System/Info?format=json
03-30 10:07:45.624 15303 15303 D com.dkanada.gramophone.App: Creating ApiWebSocket
03-30 10:07:45.625 15303 15303 D com.dkanada.gramophone.App: Connecting to web socket url: wss://example.com/socket?api_key=apiKey&deviceId=572807945a87a33d
03-30 10:07:45.632 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Sessions/Capabilities/Full
03-30 10:07:45.633 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/System/Info?format=json
03-30 10:07:45.633 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Sessions/Capabilities/Full
03-30 10:07:45.791 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Sessions/Capabilities/Full
03-30 10:07:45.791 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Sessions/Capabilities/Full
03-30 10:07:45.958 15303 19413 I com.dkanada.gramophone.App: Web socket connection opened.
03-30 10:07:45.963 15303 19413 D com.dkanada.gramophone.App: Web socket message received.
03-30 10:07:45.963 15303 19413 I com.dkanada.gramophone.App: Received web socket message: ForceKeepAlive
03-30 10:07:46.161  1210  2428 I ActivityTaskManager: START u0 {flg=0x10008000 cmp=com.dkanada.gramophone/.activities.MainActivity} from uid 10436 pid 15303
03-30 10:07:46.176  1210  9909 I ActivityTaskManager: The Process com.dkanada.gramophone Already Exists in BG. So sending its PID: 15303
03-30 10:07:46.179  1210  9909 D OpQuickReply: setQuickReplyResumed focusedApp ActivityRecord{6b91945 u0 com.dkanada.gramophone/.activities.MainActivity t10281} pkgName com.dkanada.gramophone
03-30 10:07:46.184  1210  1614 D OpRestartProcessManager: updateSelf :  com.dkanada.gramophone, size : 30
03-30 10:07:46.203  1210  1615 D OPFD_CTRL_SVC: [2]handle Starting Window for { com.dkanada.gramophone }, Dark? false
03-30 10:07:46.227 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Views?format=json
03-30 10:07:46.278 15303 15303 I chatty  : uid=10436(com.dkanada.gramophone) identical 11 lines
03-30 10:07:46.342  1210  1689 I ===> HoustonPackage: addLaunchTimeInfo: for com.dkanada.gramophone/.activities.MainActivity isCold:false launchTime:181
03-30 10:07:46.342  1210  1689 I 322     : com.dkanada.gramophone#-1#181
03-30 10:07:46.342  1210  1631 I ActivityTaskManager: Displayed com.dkanada.gramophone/.activities.MainActivity: +181ms
03-30 10:07:46.353 15303 15303 I TetheringManager: registerTetheringEventCallback:com.dkanada.gramophone
03-30 10:07:46.403 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Views?format=json
03-30 10:07:46.425 15303 19427 W SimpleExoPlayer:       at com.dkanada.gramophone.service.playback.LocalPlayer.setDataSource(LocalPlayer.java:1)
03-30 10:07:46.425 15303 19427 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService.openCurrent(MusicService.java:3)
03-30 10:07:46.425 15303 19427 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService.restoreQueuesAndPositionIfNecessary(MusicService.java:10)
03-30 10:07:46.425 15303 19427 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService.access$500(MusicService.java:1)
03-30 10:07:46.425 15303 19427 W SimpleExoPlayer:       at com.dkanada.gramophone.service.MusicService$QueueHandler.handleMessage(MusicService.java:3)
03-30 10:07:46.428 15303 19427 I com.dkanada.gramophone.util.MusicUtil: playing audio: https://example.com/Audio/354d43ad57518d7bcf8a9d0b3515b181/universal?UserId=9c53926fb82b4046b360a4776fa5c686&DeviceId=572807945a87a33d&MaxStreamingBitrate=256000&Container=mp3|mp3,mka|opus,m4a|aac,ogg|vorbis,flac|flac,opus|opus,ogg|opus&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=apiKey
03-30 10:07:46.459 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?SortBy=Random&recursive=true&IncludeItemTypes=Audio&ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
03-30 10:07:46.461 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?SortBy=Random&recursive=true&IncludeItemTypes=MusicAlbum&ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&sortOrder=Descending&Limit=100&format=json
03-30 10:07:46.464 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Artists/AlbumArtists?ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&SortBy=SortName&recursive=true&Fields=Genres&UserId=9c53926fb82b4046b360a4776fa5c686&sortOrder=Ascending&Limit=100&format=json
03-30 10:07:46.466 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Genres?ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&recursive=true&UserId=9c53926fb82b4046b360a4776fa5c686&Limit=100&format=json
03-30 10:07:46.468 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&recursive=true&Limit=100&IncludeItemTypes=Playlist&format=json
03-30 10:07:46.470 15303 15303 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?SortBy=Random&recursive=true&Filters=IsFavorite&IncludeItemTypes=Audio&ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
03-30 10:07:46.518 15303 19427 I chatty  : uid=10436(com.dkanada.gramophone) ce$QueueHandler identical 1 line
03-30 10:07:46.519 15303 19427 I chatty  : uid=10436(com.dkanada.gramophone) ce$QueueHandler identical 6 lines
03-30 10:07:46.519 15303 19426 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Sessions/Playing
03-30 10:07:46.521 15303 19427 I chatty  : uid=10436(com.dkanada.gramophone) ce$QueueHandler identical 1 line
03-30 10:07:46.526 15303 19427 I chatty  : uid=10436(com.dkanada.gramophone) ce$QueueHandler identical 4 lines
03-30 10:07:46.548 15303 19427 I chatty  : uid=10436(com.dkanada.gramophone) ce$QueueHandler identical 3 lines
03-30 10:07:46.551 15303 19425 I com.dkanada.gramophone.util.MusicUtil: playing audio: https://example.com/Audio/293ed0c89f9f9cfd5e407696a38317d7/universal?UserId=9c53926fb82b4046b360a4776fa5c686&DeviceId=572807945a87a33d&MaxStreamingBitrate=256000&Container=mp3|mp3,mka|opus,m4a|aac,ogg|vorbis,flac|flac,opus|opus,ogg|opus&TranscodingContainer=ts&TranscodingProtocol=hls&AudioCodec=aac&api_key=apiKey
03-30 10:07:46.573 15303 19426 D com.dkanada.gramophone.App: Adding request to queue: https://example.com/Sessions/Playing
03-30 10:07:46.842  4655  4655 D NotificationListener: onNotificationPosted# sbn: 74580588, package = com.dkanada.gramophone
03-30 10:07:46.843  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.843  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.883  4655  4655 D NotificationListener: onNotificationPosted# sbn: 214966325, package = com.dkanada.gramophone
03-30 10:07:46.887  4655  4655 D NotificationListener: onNotificationPosted# sbn: 208407754, package = com.dkanada.gramophone
03-30 10:07:46.891  4655  4655 D NotificationListener: onNotificationPosted# sbn: 69414459, package = com.dkanada.gramophone
03-30 10:07:46.915  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.915  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.920  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.921  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.926  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.926  2407  2407 D InterruptionStateProvider: No alerting: filtered notification: 0|com.dkanada.gramophone|1|null|10436
03-30 10:07:46.938 15303 19425 E AndroidRuntime: FATAL EXCEPTION: com.dkanada.gramophone.service.MusicService$PlaybackHandler
03-30 10:07:46.938 15303 19425 E AndroidRuntime: Process: com.dkanada.gramophone, PID: 15303
03-30 10:07:46.938 15303 19425 E AndroidRuntime:        at com.dkanada.gramophone.service.playback.LocalPlayer.appendDataSource(LocalPlayer.java:7)
03-30 10:07:46.938 15303 19425 E AndroidRuntime:        at com.dkanada.gramophone.service.playback.LocalPlayer.queueDataSource(LocalPlayer.java:3)
03-30 10:07:46.938 15303 19425 E AndroidRuntime:        at com.dkanada.gramophone.service.MusicService.prepareNextImpl(MusicService.java:4)
03-30 10:07:46.938 15303 19425 E AndroidRuntime:        at com.dkanada.gramophone.service.MusicService.access$1300(MusicService.java:1)
03-30 10:07:46.938 15303 19425 E AndroidRuntime:        at com.dkanada.gramophone.service.MusicService$PlaybackHandler.handleMessage(MusicService.java:29)
03-30 10:07:46.949  1210  4475 W ActivityTaskManager:   Force finishing activity com.dkanada.gramophone/.activities.MainActivity
03-30 10:07:46.951  1210 19438 D FrameworkEventCollector: recordAppIssue PN: com.dkanada.gramophone
03-30 10:07:46.978  1210  9909 D OpColorDisplayService: lpackageName: com.dkanada.gramophone
03-30 10:07:46.978  1210  9909 D OpProximityController: noteFrontPackageChanged pkg:com.teslacoilsw.launcher uid:10256 lpkg:com.dkanada.gramophone luid:10436
03-30 10:07:46.999 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Genres?ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&recursive=true&UserId=9c53926fb82b4046b360a4776fa5c686&Limit=100&format=json
03-30 10:07:47.026  1210  1614 D OpRestartProcessManager: Duration is too short, ignore : 790 in com.dkanada.gramophone
03-30 10:07:47.097  1210  1612 V WindowManager: Orientation start waiting for draw, mDrawState=DRAW_PENDING in Window{f47d52f u0 Application Error: com.dkanada.gramophone}, surfaceController Surface(name=Application Error: com.dkanada.gramophone)/@0xc6441d4
03-30 10:07:47.124  1210  1626 W BroadcastQueue: Skipping deliver [background] BroadcastRecord{1dd89ca u-1 android.net.conn.CONNECTIVITY_CHANGE} to ReceiverList{b65f76c 15303 com.dkanada.gramophone/10436/u0 remote:ade681f}: process gone or crashing
03-30 10:07:47.125 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Artists/AlbumArtists?ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&SortBy=SortName&recursive=true&Fields=Genres&UserId=9c53926fb82b4046b360a4776fa5c686&sortOrder=Ascending&Limit=100&format=json
03-30 10:07:47.186 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?SortBy=Random&recursive=true&IncludeItemTypes=Audio&ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
03-30 10:07:47.207 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?SortBy=Random&recursive=true&Filters=IsFavorite&IncludeItemTypes=Audio&ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&Fields=MediaSources&sortOrder=Descending&Limit=100&format=json
03-30 10:07:47.208 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&recursive=true&Limit=100&IncludeItemTypes=Playlist&format=json
03-30 10:07:47.240 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Sessions/Playing
03-30 10:07:47.289 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Sessions/Playing
03-30 10:07:47.295 15303 15303 I com.dkanada.gramophone.App: Response received from: https://example.com/Users/9c53926fb82b4046b360a4776fa5c686/Items?SortBy=Random&recursive=true&IncludeItemTypes=MusicAlbum&ParentId=c60b73cd7f4276a9ffd5395ff0ff26a7&StartIndex=0&sortOrder=Descending&Limit=100&format=json
03-30 10:07:47.774 15303 19413 D com.dkanada.gramophone.App: Web socket message received.
03-30 10:07:47.775 15303 19413 I com.dkanada.gramophone.App: Received web socket message: UserDataChanged
03-30 10:07:48.617  1210  9909 W NotificationService: Toast already killed. pkg=com.dkanada.gramophone token=android.os.BinderProxy@3708acd
```

Jellyfin's logs:
```
[2022-03-30 09:06:09.122 +00:00] [INF] [43] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: null, MaxAlbumArtHeight: null, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp3", AudioCodec: "mp3", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mka", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: "vorbis", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: "flac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "opus", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: "opus", VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2022-03-30 09:06:09.124 +00:00] [INF] [43] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User". EnableAudioPlaybackTranscoding: True
[2022-03-30 09:06:09.293 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Existing tracker found! : 572807945a87a33d-9c53926fb82b4046b360a4776fa5c686-2609bb69e4fea6e0262234762dacc080
[2022-03-30 09:06:09.294 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Removing existing tracker : 572807945a87a33d-9c53926fb82b4046b360a4776fa5c686-2609bb69e4fea6e0262234762dacc080
[2022-03-30 09:06:09.294 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 572807945a87a33d-9c53926fb82b4046b360a4776fa5c686-2609bb69e4fea6e0262234762dacc080
[2022-03-30 09:06:09.294 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 03/30/2022 09:06:09
[2022-03-30 09:06:09.294 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2022-03-30 09:06:09.294 +00:00] [INF] [31] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2022-03-30 09:06:09.359 +00:00] [INF] [34] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "138.199.15.166" request
[2022-03-30 09:06:09.414 +00:00] [INF] [31] Jellyfin.Api.Controllers.UniversalAudioController: GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: null, MaxAlbumArtHeight: null, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 8000000, MaxStaticBitrate: 8000000, MusicStreamingTranscodingBitrate: 128000, MaxStaticMusicBitrate: 8000000, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "mp3", AudioCodec: "mp3", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mka", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: "vorbis", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: "flac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "opus", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: "opus", VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: "", AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False, Conditions: [] }], ContainerProfiles: [], CodecProfiles: [], ResponseProfiles: [], SubtitleProfiles: [] }
[2022-03-30 09:06:09.426 +00:00] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for "User". EnableAudioPlaybackTranscoding: True
[2022-03-30 09:06:09.599 +00:00] [INF] [43] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Existing tracker found! : 572807945a87a33d-9c53926fb82b4046b360a4776fa5c686-2609bb69e4fea6e0262234762dacc080
[2022-03-30 09:06:09.599 +00:00] [INF] [43] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Removing existing tracker : 572807945a87a33d-9c53926fb82b4046b360a4776fa5c686-2609bb69e4fea6e0262234762dacc080
[2022-03-30 09:06:09.599 +00:00] [INF] [43] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Adding playback tracker : 572807945a87a33d-9c53926fb82b4046b360a4776fa5c686-2609bb69e4fea6e0262234762dacc080
[2022-03-30 09:06:09.599 +00:00] [INF] [43] Jellyfin.Plugin.PlaybackReporting.Data.PlaybackTracker: PlaybackTracker : Adding Start Event : 03/30/2022 09:06:09
[2022-03-30 09:06:09.599 +00:00] [INF] [43] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: Creating StartPlaybackTimer Task
[2022-03-30 09:06:09.599 +00:00] [INF] [43] Jellyfin.Plugin.PlaybackReporting.EventMonitorEntryPoint: StartPlaybackTimer : Entered
[2022-03-30 09:06:09.628 +00:00] [WRN] [31] Emby.Server.Implementations.HttpServer.WebSocketConnection: WS "138.199.15.166" error receiving data: "The remote party closed the WebSocket connection without completing the close handshake."
[2022-03-30 09:06:09.632 +00:00] [INF] [31] Emby.Server.Implementations.HttpServer.WebSocketManager: WS "138.199.15.166" closed
```

**Comment by vicky5124** [comment] 2022-04-08 13:47
Can reproduce in `10.7.7` (`:latest` as of writing) with docker instead of podman, except it doesn't crash for me, it just lags and shows the error message afterwards. Direct playing also fixes it.

**Comment by dkanada** [comment] 2022-04-08 14:31
@vicky5124 can you confirm 10.7.6 works while 10.7.7 doesn't work when transcoding on the latest version of Gelli? That would hugely narrow down the scope of the issue. Someone basically needs to go through and bisect the server to find out what change broke the app or step through the codebase here to find the root cause. Not quite sure yet which one would be more efficient.

**Comment by vicky5124** [comment] 2022-04-13 00:18
The issue persists on `10.7.6`

`docker run -d -v /srv/jellyfin/config:/config -v /srv/jellyfin/cache:/cache -v /mnt/storage/media:/media --group-add=989 --net=host --restart=unless-stopped --device /dev/dri/renderD128:/dev/dri/renderD128 --device /dev/dri/card0:/dev/dri/card0 --name jellyfin jellyfin/jellyfin:10.7.6`

**Comment by jakobkukla** [comment] 2022-04-24 10:17
I can't reproduce this on master. Seems like my playback changes might have fixed this issue by coincidence. 

@vicky5124 @Pecomare Could you check if the issue still persists for you on Gelli master? Note: 10.7 might not work since the changes in master require a bug fix in 10.8.

**Comment by vicky5124** [comment] 2022-04-24 14:30
I'd love to try it, but I'm struggling to build an APK from source.

Using gradle 7.4.2, generating the keystore with
`keytool -genkey -v -keystore keystore.jks -alias gelli -keyalg RSA -keysize 2048 -validity 10000`
and building with
`gradle assemble`
leads to this:

```
* What went wrong:
Execution failed for task ':app:mergeDexDebug'.
> A build operation failed.
      java.nio.charset.MalformedInputException: Input length = 1
   > java.nio.charset.MalformedInputException: Input length = 1
```

And I can't seem to find any information about how to fix this.

I'd be nice if CI released the APK as an artefact when pushed to master, with some script that will remove older artefacts to save on storage.

**Comment by Pecomare** [comment] 2022-04-24 17:01
I tested master on Android Studio and on my phone using the debug apk generated (I have no experience with Android dev) and it seemed to be working with Jellyfin 10.8.0-beta2.

**Comment by jakobkukla** [comment] 2022-04-24 17:55
Thanks for the feedback. I think we can close this now @dkanada :)

**Closed** 2022-04-25 04:26 UTC
