### ISSUE TITLE
Feature Request: Maximum Bitrate/Transcode settings based on connection

### ISSUE THREAD

**Issue by baarkerlounger** [dkanada/gelli#73] opened 2020-08-16 15:12 UTC
Would be handy to be able to set Maximum Bitrate and Transcode Settings to be different based on whether you're connected to WiFi or data.

**Comment by dkanada** [comment] 2020-08-29 06:46
I'll close this as a duplicate of #15 so the feature request can be tracked over there.

**Closed by dkanada** 2020-08-29 06:46 UTC
