### ISSUE TITLE
Caching?

### ISSUE THREAD

**Issue by spiral6** [dkanada/gelli#28] opened 2020-06-28 00:50 UTC
It would be nice to see if caching is a feature you could support. Sometimes, instead of just pure offline downloads, it would be nice to cache songs (i.e. from listening to a playlist).

**Comment by ExNG** [comment] 2020-07-08 11:10
I agree, it would also save a lot of bandwidth when listening only to a few songs in a loop ^^

**Comment by KristupasSavickas** [comment] 2020-07-09 06:58
Looks like exoplayer supports caching to some extent, so this should be doable. Maybe parts of the implementation for caching could be reused for offline download functionality.

**Comment by dkanada** [comment] 2020-07-09 07:16
That was indeed my plan. I was going to add a recents cache with a configurable limit and then a download functionality that pushed songs to another directory for persistent storage.

**Comment by screwfaze** [comment] 2020-07-23 21:12
Please make this a priority as would mean we can use this app as the main music player on android.

**Comment by dkanada** [comment] 2020-11-03 14:12
I added recents caching in the latest update, so I think this issue can be closed. True offline downloads aren't supported yet but I think it's covered in other open issues.

**Comment by SightSpirit** [comment] 2021-01-30 20:12
(Putting this here since the issue is still listed as open.)

**Comment by SightSpirit** [comment] 2021-01-30 20:17
(Putting this here since issue is still listed as open.)

I don't have a lot of free space on my phone, so I'd like to be able to disable caching entirely for either images or audio or both. I have no pressing need to cache images, so I would like to be able to limit it to less than 100MB or disable caching entirely.

When Gelli supports offline playback, I'll probably wind up disabling audio caching; as it stands, I can't tell what songs are cached or not, so I don't use Gelli when I'm not connected to Wi-Fi.

**Comment by spiral6** [comment] 2021-02-01 00:29
Setting a maximum size for the cache or a max in regards to the number of songs would be nice.

**Comment by ainola** [comment] 2021-04-15 20:09
Thank you for your work on this, dkanada!

Forgive me, but what issue tracks the FR of selecting albums/tracks for caching? You mentioned closing this in lieu of such an issue but I'm unable to locate it...

**Comment by strugee** [comment] 2021-04-16 01:57
#41

**Comment by dkanada** [comment] 2021-04-16 02:53
I'm currently working on multi-server, which is tangentially related to offline mode in case anyone wants an update. It's technically finished, but I'm trying to start a UI redesign before the next release.

The next step would be moving the authentication into an event-driven service to avoid that annoying crash on resume, which is extremely important for offline mode. After that, the only thing left would be adding everything we need into the database.

**Comment by dkanada** [comment] 2021-04-16 02:55
Of course, I'm leaving out the download service and all the UI changes required to support offline, but as you can tell those are further down the pipeline than I'm currently planning.

**Comment by strugee** [comment] 2021-04-19 04:28
@dkanada congrats on that progress! That's really awesome. And thanks for spending so much time maintaining this app - I for one really appreciate your hard work. I know it can often feel thankless but you've made my life measurably better :)

**Comment by dkanada** [comment] 2021-05-19 10:37
I will close this issue since caching has been available for a while and downloads are now also available. My current plan is to add a few minor releases with smaller improvements like custom download directories and simultaneous downloads, and then releasing 1.4.0 with proper offline support. This plan may change, I just wanted to provide a general update.

**Closed by dkanada** 2021-05-19 10:37 UTC
