### ISSUE TITLE
Epileptic full screen flashing lights when opening/closing the app

### ISSUE THREAD

**Issue by IceCloud76** [dkanada/gelli#130] opened 2021-03-15 23:39 UTC
Sometimes when I open Gelli, the app will create a full screen white background which will then change to a black background, and then back again to white, every quarter of a second or so creating a a flashing lights effect. This could cause some problems with people who have  epilepticy. 

Sometimes this happens when I close the app, but I haven't found a way to reproduce the issue yet

Steps to reproduce:  

1. Open Gelli
2. Open multitasking and close the app
3. Swipe away the Gelli notification
4. Open Gelli and the flashing occurs  

Phone: Oneplus 5T Lineage OS on Android 9

**Comment by dkanada** [comment] 2021-03-16 01:28
This is actually unintentional behavior with a crash somewhere, but I haven't been able to find the cause yet.

**Comment by Saladaa** [comment] 2021-03-18 11:12
On my phone, this occurs every time I open the app and try to login, without fail. Sometimes it softlocks my phone as well, preventing me from returning to the homescreen or opening any other application, forcing me to restart.

Reinstalling, emptying the cache+local storage, and everything else I could think of to prevent this crash from happening did not work.

Good luck finding the cause, look forward to using Gelli again :)

**Comment by dkanada** [comment] 2021-03-18 15:44
The flashing seems to be a result of the new crash activity but the root cause of the crash can also be found in #58 and might take a while to fix. It basically requires the login flow to become completely async, and rewriting any section of code that calls the server to listen and wait for authentication rather than expect it.

I'll probably remove the crash activity for now on production builds to avoid the flashing. Coincidentally, the tasks outlined above were the next items on my list whenever I can find some time.

**Comment by dkanada** [comment] 2021-04-27 04:31
I believe this crash should be resolved in the latest update, can anyone confirm?

**Comment by Saladaa** [comment] 2021-04-27 09:07
> I believe this crash should be resolved in the latest update, can anyone confirm?

Thank you :)
I'm currently completely redoing my home server, but I'll report back once I have Jellyfin setup again.

**Comment by niftium** [comment] 2021-04-27 13:00
I haven't been able to trigger it again since the update.

**Comment by IceCloud76** [comment] 2021-04-27 13:29
I haven't been using Gelli for a while because of this issue, but I just started using it again a few days ago and haven't seen this bug since.

I've also tried reproducing the bug with the steps I detailed above and it seems to have been fixed :)

**Comment by dkanada** [comment] 2021-04-27 14:50
I didn't notice the search issue until now, but I'll push a hotfix tomorrow to solve it. You can tell I don't use the search that often haha.

**Comment by dkanada** [comment] 2021-04-28 01:14
New release is up on GitHub, let me know if the search is still broken or not. Works on my machine :p

**Comment by niftium** [comment] 2021-04-28 01:56
Fixed!

**Closed** 2021-05-26 06:58 UTC
