### ISSUE TITLE
Shuffle all on favorites doesn't shuffle favorites

### ISSUE THREAD

**Issue by DomiStyle** [dkanada/gelli#179] opened 2021-07-27 06:50 UTC
There are 2 shuffle all buttons in Gelli, one on the "Songs" page, which shuffles the whole library as expected but there's another one in "Favorites" which does not shuffle just the favorites but also the whole library.

It would be nice if it would be possible to shuffle only the favorites this way.

**Comment by gordyhike** [comment] 2021-08-16 15:56
I would like to suggest that there is an option to shuffle all for each of the group selections... eg shuffle Full library, shuffle chosen folder, genre, artist, album etc.. I tried 'shuffle all' from in a folder, but it shuffled all items from all folders in my library.

**Comment by dkanada** [comment] 2021-10-05 12:10
@DomiStyle this looks like a duplicate of #150 to me. @gordyhike I'm not sure how you managed to shuffle from a folder within Gelli because it doesn't support folder views.

**Comment by gordyhike** [comment] 2021-10-05 16:45
@dkanada There may not be folder support directly but let me explain.
I store my music in separate folders depending on who's music it is.
eg  My music, Ann's music, John's music, etc Family like their own genres.
And this is set up in Jellyfin as you do... My Media libraries, One each.
Then this is set up Artist/Album etc. all tagged properly.

Gelli can see this and presents each library separately..
Within Gelli, you can then tap the Burger menu, top left and Gelli lists your libraries (My music, Anns music, Johns music, etc)
tap one to select your chosen library and you see just that library eg Ann's music
Albums, Artists, and songs from that library.

Now if I select songs in the library, I see just the songs from that library and there is a Shuffle All at the top of the list.
I would expect this to shuffle all the songs in this library eg songs in Ann's Music. Which it does not. They are all you see in the library but shuffle all gathers songs from the full, multiple libraries.

Now if I tap the three dots (top right) there is another shuffle all.
Now I would expect this option to shuffle 'All' (full, multiple libraries), which it does.

I think 'Songs/shuffle all' is the only option needed for the library as 'album/shuffle all' and 'artist/shuffle all' is essentially the same thing. You can shuffle an Album or an Artist when you have selected it
'Favorites' is essentially another library and should be treated as such.
And use the three Dots/shuffle all to shuffle everything.



Finamp does shuffle songs in a library..

tap Burger menu, top left, and Finamp lists your libraries (the same as Gelli.. My music, Ann's music, Johns music, etc)
tap to select your library and you see just that library (the same as Gelli..) Artists, Artists, and songs from that library.

select songs and there is a shuffle all button (bottom right), which shuffles the current library - perfect
But in Finamp, there isn't an option to shuffle everything.

I like the Gelli interface but this issue niggles at me.
It's not a problem as I can use Finamp, but I like to use Gelli.

Thanks

**Comment by gordyhike** [comment] 2021-10-05 17:02
PS It looks like Favorites behaves the same..
Favorites apply to each individual library. eg favorite 'songs' for Ann's music. John's music would be a different list of favorites.
again the 'Shuffle All' at the top of the list should shuffle the list... It does not.

Thanks

**Closed** 2023-03-04 11:15 UTC

**Comment by gordyhike** [comment] 2023-03-04 12:08
Hi,
I still think this shuffle issue is still a problem


In Jellyfin I have multiple music libraries..
   Johns Music
   Sues Music
   Alisons Music
   
  Gelli can see these seperate libraries..
  Gelli main screen..
  Tap the hamburger menu (Top Left)
  the music libraries are listed...
  
  If I select 'Johns music', then 'songs' on the top menu bar, All the songs in 'Johns Music' is displayed. (as it should be). No songs from 'Sues Music' or 'Alisons Music' are included.
  
  There are now two 'shuffle All' options.
  First, Three dots (top right) - Shuffle All
  Selecting this option shuffles All the songs from 'All the libraries, including Johns, Sues and Alisons.
  This should be 'Shuffle Everything'
  
  The second option is 'Shuffle All' at the top of the songs list. This perhaps should be labelled 'Shuffle Library Songs'.
  I would expect this option to shuffle the songs listed eg 'Johns Music' but it doesn't. It again shuffles 'All' the songs from 'All the libraries, including Johns, Sues and Alisons.
  Surely this is wrong.
  
  I like Gelli and use it from time to time, but this spoils it for me.
  Finamp 'does' shuffle only the songs in the listed library so it works for me.
  
  Is it possible you could revisit this issue and maybe review this function?
  
  Many Thanks
  gordyhike
