### ISSUE TITLE
Playing song from an album play the wrong one

### ISSUE THREAD

**Issue by chmol** [dkanada/gelli#11] opened 2020-06-14 11:11 UTC
step to reproduce:

+ find a album you like
+ play "song A"
+ the song played will be "song B" from the same album

If song A is played on the web client (didn't try elsewhere) and we retry playing song A on gelli it will succeed.

**Comment by DJWhitegold** [comment] 2020-06-15 17:18
Same issue here. Select a song to play and plays the following one, but displays the name of the track originally selected.

**Comment by dkanada** [comment] 2020-06-15 18:41
What version are your servers? Also, is the shuffle currently enabled or disabled in the player fragment? The logic behind that button is a bit complex so it could be the cause.

**Comment by DJWhitegold** [comment] 2020-06-16 10:35
> What version are your servers? Also, is the shuffle currently enabled or disabled in the player fragment? The logic behind that button is a bit complex so it could be the cause.
Thanks for your reply... 
Server v10.5.5. 
Shuffle disabled.

**Comment by dkanada** [comment] 2020-06-16 11:58
I actually think this might be resolved with the next server update, but I'm not sure.

**Comment by dkanada** [comment] 2020-06-18 22:33
Have you disabled battery optimizations for this app? I noticed the queue will only advance forward two songs when the screen is off during playback due to that setting.

**Comment by DJWhitegold** [comment] 2020-06-19 10:16
I reinstalled yesterday and have not optimised the app for battery use (android 10). Just tested playback of an album with the screen off and it played perfectly to the end.

The issue that I have is that often, I'll select a track, say #3 (for Example) and it will play the next one ie. #4

The app seems more stable than the previous version I tried so thanks for the improving it.

**Comment by KevinNThomas** [comment] 2020-07-07 08:25
I'm currently encountering this bug on Android 10 as well. Selecting songs one by one in an album frequently produces the wrong result.

**Comment by Harteex** [comment] 2020-07-25 22:31
This is happening to me too, and it plays the wrong song more often than the correct one.

The strange thing is that it will still think it is playing the first song, and use the song length from that one.
Let's say the intro (first song) is 01:00 and the second song is, well 03:00 or something. It will then play the second song, but change to next one minute into it.

How to reproduce for me:
1) Go to the album tab
2) Click on one of the albums
3) Click the first song in the album

This is happening on both my Android 10 and Android 7 phone.

**Comment by bendardenne** [comment] 2020-08-03 21:17
I think this is due to a race condition in `MultiPlayer`. When you click on the first track of an album, three calls to `appendDataSource` are made:

* One for the first track that needs to played  (next = true), from `MusicService#openCurrent`   l.483     
* One for preparing the next track (next = false), from `MusicService#handleChangleInternal`  l.1053,  because of the `QUEUE_CHANGED` event
* One again for preparing the next track (next = false) from `MusicService#onTrackStarted`    l 1085 after the first track starts playing

In `appendDataSource`, an HTTP request is made and the result is appended to the `ConcatenatingMediaSource`. If by chance, the request for the second track finished before the first one, it will be append to the media source first. Then the request for the first track finishes, it's added to the media source, and playback is started but the media source is in an incorrect state where the first track is in second position. 

I can reproduce the bug reliably by introducing a fake delay for the first track in `appendDataSource`

```java
                if (next) {
                    try {
                        Thread.sleep(5000);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }

                mediaSource.addMediaSource(source);
```

Using a SingleThreadedExecutor on the http client of MultiPlayer seems to reliably solve the issue. There might be a better way, like keeping track of the requests order and inserting them to the composite media source in the right order. Not sure these http requests really gain a lot from being done concurrently though.

**Comment by dkanada** [comment] 2020-08-03 22:10
@bendardenne thanks for finding the cause! I think I found a way to keep asynchronous loading and avoid a single thread. I'll push the changes soon for testing.

**Comment by dkanada** [comment] 2020-08-29 06:46
I believe this is resolved so I'll close the issue.

**Closed by dkanada** 2020-08-29 06:46 UTC
