### ISSUE TITLE
How to play an album with songs in the normal order?

### ISSUE THREAD

**Issue by AndreCarvalho** [dkanada/gelli#25] opened 2020-06-22 21:02 UTC
Hi,  when I start playing an album the play queue displays the songs in a non sequential orde

**Comment by dkanada** [comment] 2020-06-23 03:28
This is a duplicate of #11 so please track progress from there.

**Comment by dkanada** [comment] 2020-06-23 03:29
Unless you're talking about the shuffle feature? In which case, you can fix the order by turning off shuffle from the now playing screen.

**Closed by dkanada** 2020-06-23 03:28 UTC

**Comment by AndreCarvalho** [comment] 2020-06-23 10:57
Re-installing the app seems to have fixed this. Thanks
